spring.application.name=Webpay Plus API
server.port=8080

# ⚠️ CRÍTICO: Configurar para que Spring respete X-Forwarded-* headers del ALB
# Esto es esencial para que returnUrl se construya con HTTPS en AWS
# comenta esto si quieres control total
# server.tomcat.remoteip.protocol-header=X-Forwarded-Proto
# server.tomcat.remoteip.remote-ip-header=X-Forwarded-For
#server.tomcat.remoteip.protocol-header-https-value=https
server.forward-headers-strategy=none

# Webpay Configuration - Integration Environment
transbank.commerce.code=597055555532
transbank.api.key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
transbank.environment=INTEGRATION

# Logging
logging.level.root=INFO
logging.level.com.webpaytest.api=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Payment Provider selection: WEBPAY or MP
payment.provider=MP

# MercadoPago configuration (use env vars in deployment)
mp.access.token=TEST-6748671072773401-061317-d31d1aa5de5aee7e1b10b70ff44098b3-3472645856
mp.success.url=http://nicolasmendez.cl/success
mp.failure.url=http://nicolasmendez.cl/failure
mp.pending.url=http://nicolasmendez.cl/pending